import type { EnemyDef, HeroDef, PathAction } from "./types.ts";

export const PATH_LABEL: Record<PathAction, string> = {
  challenge: "挑戰",
  inquire: "探聽",
  allure: "勸誘",
  purchase: "購買",
  guide: "帶領",
  hire: "延聘",
  provoke: "威嚇",
  duel: "決鬥",
};

export const WEAPON_LABEL = {
  sword: "刀",
  spear: "槍",
  bow: "弓",
  fan: "扇",
  fire: "火",
  staff: "杖",
  dark: "暗",
} as const;

export const HEROES: HeroDef[] = [
  {
    id: "guanyu",
    name: "關羽",
    title: "武聖",
    job: "saint",
    jobName: "青龍刀客",
    pathAction: "challenge",
    pathActionName: "挑戰",
    opening: "關羽自解州動身，只為尋一位值得託付的主公。刀還沒出鞘，義氣先到了新野。",
    bio: "刀技連斬。路徑行動是挑戰，可立刻把對手拉進戰場。蓄力後青龍斬最能削盾。",
    portrait: "./art/portrait-guanyu.png",
    color: "#2f6b46",
    maxHp: 128,
    maxSp: 36,
    atk: 22,
    def: 12,
    spd: 12,
    weaknesses: ["bow", "fire"],
    skills: [
      { id: "dragon-slash", name: "青龍斬", sp: 8, weapon: "sword", hits: 2, power: 1.15 },
      { id: "righteous", name: "義氣", sp: 10, weapon: "sword", hits: 1, power: 0.4, effect: "bpAlly" },
      { id: "spring", name: "溫酒", sp: 14, weapon: "sword", hits: 3, power: 0.85 },
    ],
    supportSkill: { id: "sup-cover", name: "義護", sp: 6, weapon: "sword", hits: 0, power: 0, effect: "cover", support: true },
  },
  {
    id: "zhaoyun",
    name: "趙雲",
    title: "常山",
    job: "dragon",
    jobName: "龍槍",
    pathAction: "duel",
    pathActionName: "決鬥",
    opening: "趙雲白馬銀槍，在新野城門前勒住韁繩。他要確認，這座小城還能不能保住百姓。",
    bio: "槍擊次數多，一次就能把盾削光。決鬥可點名單挑。",
    portrait: "./art/portrait-zhaoyun.png",
    color: "#8ec4e8",
    maxHp: 110,
    maxSp: 40,
    atk: 20,
    def: 10,
    spd: 16,
    weaknesses: ["dark", "fire"],
    skills: [
      { id: "seven", name: "七進七出", sp: 12, weapon: "spear", hits: 4, power: 0.55 },
      { id: "white-horse", name: "白馬突", sp: 8, weapon: "spear", hits: 1, power: 1.35 },
      { id: "cover", name: "護主", sp: 9, weapon: "spear", hits: 1, power: 0.3, effect: "heal" },
    ],
    supportSkill: { id: "sup-heal", name: "援護", sp: 6, weapon: "spear", hits: 0, power: 0, effect: "heal", support: true },
  },
  {
    id: "zhangfei",
    name: "張飛",
    title: "虓虎",
    job: "tiger",
    jobName: "虓虎",
    pathAction: "provoke",
    pathActionName: "威嚇",
    opening: "張飛把蛇矛往地上一頓，新野的酒旗都跟著顫。他來這裡，是聽說有人敢攔路。",
    bio: "吼聲打整排。威嚇能讓對手先露出破綻。",
    portrait: "./art/portrait-zhangfei.png",
    color: "#5b3a2e",
    maxHp: 142,
    maxSp: 28,
    atk: 24,
    def: 14,
    spd: 9,
    weaknesses: ["fan", "bow"],
    skills: [
      { id: "roar", name: "喝退", sp: 10, weapon: "spear", hits: 1, power: 0.8, aoe: true },
      { id: "snake", name: "蛇矛連", sp: 9, weapon: "spear", hits: 3, power: 0.7 },
      { id: "bridge", name: "當陽", sp: 16, weapon: "spear", hits: 1, power: 1.9 },
    ],
    supportSkill: { id: "sup-cover", name: "護陣", sp: 5, weapon: "spear", hits: 0, power: 0, effect: "cover", support: true },
  },
  {
    id: "zhuge",
    name: "諸葛亮",
    title: "臥龍",
    job: "scholar",
    jobName: "軍師",
    pathAction: "inquire",
    pathActionName: "探聽",
    opening: "諸葛亮把羽扇合上。新野的風向、糧草、城門守備，他在進門前就已算過一遍。",
    bio: "探聽可知弱點。火計打中弱點後，盾會很快被削開。",
    portrait: "./art/portrait-zhuge.png",
    color: "#cfc7a4",
    maxHp: 88,
    maxSp: 56,
    atk: 18,
    def: 8,
    spd: 14,
    weaknesses: ["sword", "dark"],
    skills: [
      { id: "fire-plan", name: "火計", sp: 11, weapon: "fire", hits: 1, power: 1.4, aoe: true, effect: "burn" },
      { id: "see-through", name: "看破", sp: 6, weapon: "fan", hits: 1, power: 0.2, effect: "reveal" },
      { id: "east-wind", name: "東風", sp: 14, weapon: "fire", hits: 2, power: 1.05, aoe: true },
    ],
    supportSkill: { id: "sup-reveal", name: "觀微", sp: 5, weapon: "fan", hits: 0, power: 0, effect: "reveal", support: true },
  },
  {
    id: "caocao",
    name: "曹操",
    title: "魏武",
    job: "hegemon",
    jobName: "霸王",
    pathAction: "purchase",
    pathActionName: "徵購",
    opening: "曹操站在新野城樓的影子裡。他要把這條路變成自己的路。",
    bio: "令箭給隊友蓄力。徵購可直接換來物資。",
    portrait: "./art/portrait-caocao.png",
    color: "#7a1f2b",
    maxHp: 118,
    maxSp: 42,
    atk: 19,
    def: 11,
    spd: 13,
    weaknesses: ["staff", "spear"],
    skills: [
      { id: "order", name: "令箭", sp: 8, weapon: "dark", hits: 1, power: 0.3, effect: "bpAlly" },
      { id: "hegemon-blow", name: "奸雄一擊", sp: 12, weapon: "sword", hits: 1, power: 1.7 },
      { id: "jizhou", name: "挾令", sp: 11, weapon: "dark", hits: 1, power: 0.6, effect: "debuffAtk" },
    ],
    supportSkill: { id: "sup-cover", name: "督陣", sp: 6, weapon: "dark", hits: 0, power: 0, effect: "cover", support: true },
  },
  {
    id: "zhouyu",
    name: "周瑜",
    title: "公瑾",
    job: "flame",
    jobName: "火神",
    pathAction: "hire",
    pathActionName: "延聘",
    opening: "周瑜聽新野城裡有人吹笛，音律不穩。他笑了一下：亂世的前奏，總是這樣起的。",
    bio: "火攻打一片。延聘可把路人請入隊伍片刻。",
    portrait: "./art/portrait-zhouyu.png",
    color: "#c45c3a",
    maxHp: 100,
    maxSp: 50,
    atk: 21,
    def: 9,
    spd: 15,
    weaknesses: ["staff", "bow"],
    skills: [
      { id: "fire-attack", name: "火攻", sp: 12, weapon: "fire", hits: 2, power: 0.9, aoe: true, effect: "burn" },
      { id: "melody", name: "琴心", sp: 8, weapon: "fan", hits: 1, power: 0.35, effect: "heal" },
      { id: "red-cliff", name: "赤壁", sp: 18, weapon: "fire", hits: 3, power: 0.8, aoe: true },
    ],
    supportSkill: { id: "sup-heal", name: "撫軍", sp: 6, weapon: "fan", hits: 0, power: 0, effect: "heal", support: true },
  },
  {
    id: "sunshangxiang",
    name: "孫尚香",
    title: "弓姬",
    job: "archer",
    jobName: "弓姬",
    pathAction: "guide",
    pathActionName: "帶領",
    opening: "孫尚香把弓弦拉滿又鬆開。新野的城垛太矮，她已經看見城外那一撮黃巾。",
    bio: "弓箭專打弱點。帶領可把人帶離危險位置。",
    portrait: "./art/portrait-sunshangxiang.png",
    color: "#b43c3c",
    maxHp: 96,
    maxSp: 38,
    atk: 21,
    def: 8,
    spd: 17,
    weaknesses: ["spear", "dark"],
    skills: [
      { id: "rain", name: "箭雨", sp: 11, weapon: "bow", hits: 3, power: 0.6, aoe: true },
      { id: "weak-shot", name: "破的", sp: 7, weapon: "bow", hits: 1, power: 1.25 },
      { id: "tiger", name: "虎女", sp: 13, weapon: "bow", hits: 2, power: 1.1 },
    ],
    supportSkill: { id: "sup-reveal", name: "破隱", sp: 5, weapon: "bow", hits: 0, power: 0, effect: "reveal", support: true },
  },
  {
    id: "diaochan",
    name: "貂蟬",
    title: "閉月",
    job: "dancer",
    jobName: "舞姬",
    pathAction: "allure",
    pathActionName: "勸誘",
    opening: "貂蟬在新野的燈下停住。有些仗若不先動手，就會落到別人身上。",
    bio: "勸誘能問出隱藏的話。鼓舞可為隊友回復氣力。",
    portrait: "./art/portrait-diaochan.png",
    color: "#c9a0d4",
    maxHp: 92,
    maxSp: 48,
    atk: 16,
    def: 7,
    spd: 18,
    weaknesses: ["sword", "fire"],
    skills: [
      { id: "charm", name: "迷魂", sp: 9, weapon: "dark", hits: 1, power: 0.7, effect: "debuffAtk" },
      { id: "dance", name: "鼓舞", sp: 10, weapon: "fan", hits: 1, power: 0.5, effect: "heal" },
      { id: "moon", name: "閉月", sp: 12, weapon: "dark", hits: 2, power: 0.75, aoe: true },
    ],
    supportSkill: { id: "sup-heal", name: "慰心", sp: 5, weapon: "fan", hits: 0, power: 0, effect: "heal", support: true },
  },
  {
    id: "liubei",
    name: "劉備",
    title: "昭烈",
    job: "hegemon",
    jobName: "仁君",
    pathAction: "hire",
    pathActionName: "延聘",
    opening: "劉備自涿郡來到新野。桃園之誓猶在耳——要延攬人心，先安這一城的百姓。",
    bio: "仁德延聘。路徑行動是延聘，可把有志之士請入同行。勸誘亦合其風。",
    portrait: "./art/portrait-liubei.png",
    color: "#c4a35a",
    maxHp: 120,
    maxSp: 40,
    atk: 18,
    def: 11,
    spd: 13,
    weaknesses: ["dark", "bow"],
    skills: [
      { id: "benevolent", name: "仁心", sp: 8, weapon: "sword", hits: 1, power: 0.45, effect: "heal" },
      { id: "rally-oath", name: "桃園誓", sp: 10, weapon: "sword", hits: 1, power: 0.35, effect: "bpAlly" },
      { id: "dual-blade", name: "雙股劍", sp: 12, weapon: "sword", hits: 2, power: 1.05 },
    ],
    supportSkill: { id: "sup-heal", name: "撫民", sp: 6, weapon: "sword", hits: 0, power: 0, effect: "heal", support: true },
  },
];

export const PARTNER: Record<string, string> = {
  guanyu: "zhangfei",
  zhaoyun: "sunshangxiang",
  zhangfei: "guanyu",
  zhuge: "zhouyu",
  liubei: "guanyu",
  caocao: "zhuge",
  zhouyu: "sunshangxiang",
  sunshangxiang: "zhaoyun",
  diaochan: "caocao",
};

/** Third temporary companion from the Xinyue wayfarer encounter. */
export const TRAVELER: Record<string, string> = {
  guanyu: "zhaoyun",
  zhaoyun: "zhuge",
  zhangfei: "zhouyu",
  zhuge: "guanyu",
  caocao: "zhangfei",
  zhouyu: "zhuge",
  sunshangxiang: "diaochan",
  diaochan: "zhouyu",
};

/** Extra dialogue unlocked after successful inquire/allure on that NPC. */
export const INQUIRED_TALK: Record<string, string[]> = {
  elder: [
    "里長壓低聲音：城門左側柴堆後，還藏著第二撥人。削盾後再衝。",
    "弱點記在列傳裡了。今晚若再探，我只能再說一遍。",
  ],
  drinker: ["酒客抹嘴：城門那兩個，一個怕槍、一個怕火。你記住就行。"],
  singer: ["歌女把扇骨一點：頭目愛聽軟話。有人肯勸，盾會先鬆一寸。"],
  vendor: ["商販指了指北：官道上有傷兵，肯延聘的話，或許願意跟一程。"],
  watch: ["更夫把燈罩低：夜里官道咳嗽聲不對。先把城門清了再聽。"],
  child: ["孩童搓著手：阿娘在營寨火堆邊。你們去的話，帶她回來。"],
  innkeeper: ["掌櫃點頭：今夜免費。選投宿一夜，氣血會回來。天亮再出城也不遲。"],
  bard: ["琴師輕聲：渠帥夜里喝酒。有人能勸，比硬闖省事。"],
  traveler: ["傷兵喘勻：校尉巡路，渠帥坐最裡頭。盾厚，先削再打。"],
  wayfarer: [
    "過路旅人拍了拍行囊：我也往北。若你們不嫌，我可短暫同行。",
    "三人並肩，城門與北營都好走些。",
  ],
  captive: ["婦人握住布繩：火堆旁還有路。帶我離開就好。"],
  lookout: ["校尉冷笑：再近一步，就在營裡動手。"],
  "yz-elder": ["驛丞低聲：小帥怕槍與火。削盾後再衝。"],
  "yz-vendor": ["鐵匠點頭：精鐵槍裝上，銀槍會更沉。"],
  "yz-scout": ["斥候比了比北：平野盡頭那格有旗，就是頭目。"],
  "yz-wounded": ["傷卒抹汗：遭遇滿了會有雜兵，別慌。"],
  "zg-elder": [
    "村老點頭：偽軍師陣眼在北旗左三步。火計打中，盾先鬆。",
    "探得的虛實已記在見聞。出岡上郊野即可。",
  ],
  "zg-scholar": ["書生合卷：偽軍師怕火與扇。看破之後再上。"],
  "zg-scout": ["斥候比劃：北端 BBB 旗下就是頭目。"],
  "zg-wounded": ["傷卒：探聽過再動手，他腿先軟。"],
  "zf-elder": ["驛丞：鎮口頭目怕威嚇。"],
  "zf-scout": ["斥候：吼一聲再上。"],
};

export const ENEMIES: Record<string, EnemyDef> = {
  yellow: {
    id: "yellow",
    name: "黃巾卒",
    portrait: "./art/portrait-yellowturban.png",
    maxHp: 64,
    maxSp: 12,
    atk: 12,
    def: 6,
    spd: 8,
    shields: 2,
    weaknesses: ["sword", "fire", "bow"],
    skills: [{ id: "club", name: "棒擊", sp: 0, weapon: "staff", hits: 1, power: 1 }],
    gold: 12,
    exp: 18,
  },
  archer: {
    id: "archer",
    name: "黃巾弓手",
    portrait: "./art/portrait-yellowturban.png",
    maxHp: 52,
    maxSp: 16,
    atk: 14,
    def: 5,
    spd: 13,
    shields: 2,
    weaknesses: ["spear", "sword", "fire"],
    skills: [{ id: "shot", name: "亂箭", sp: 0, weapon: "bow", hits: 1, power: 1 }],
    gold: 14,
    exp: 20,
  },
  bandit: {
    id: "bandit",
    name: "山賊頭目",
    portrait: "./art/portrait-bandit.png",
    maxHp: 110,
    maxSp: 20,
    atk: 16,
    def: 9,
    spd: 10,
    shields: 4,
    weaknesses: ["spear", "fire", "fan"],
    skills: [
      { id: "slash", name: "砍殺", sp: 0, weapon: "sword", hits: 1, power: 1 },
      { id: "heavy", name: "蠻力", sp: 6, weapon: "sword", hits: 2, power: 0.85 },
    ],
    gold: 28,
    exp: 40,
  },
  officer: {
    id: "officer",
    name: "巡營校尉",
    portrait: "./art/portrait-officer.png",
    maxHp: 96,
    maxSp: 18,
    atk: 17,
    def: 11,
    spd: 11,
    shields: 3,
    weaknesses: ["fan", "fire", "bow"],
    skills: [
      { id: "cut", name: "軍刀", sp: 0, weapon: "sword", hits: 1, power: 1 },
      { id: "drill", name: "整隊", sp: 8, weapon: "sword", hits: 1, power: 0.4, effect: "bpAlly" },
    ],
    gold: 32,
    exp: 48,
  },
  lieutenant: {
    id: "lieutenant",
    name: "黃巾小帥",
    portrait: "./art/portrait-bandit.png",
    maxHp: 96,
    maxSp: 16,
    atk: 13,
    def: 7,
    spd: 10,
    shields: 3,
    weaknesses: ["spear", "fire", "bow"],
    skills: [
      { id: "swing", name: "橫劈", sp: 0, weapon: "sword", hits: 1, power: 1 },
      { id: "bellow", name: "恫嚇", sp: 6, weapon: "dark", hits: 1, power: 0.55 },
    ],
    gold: 40,
    exp: 55,
  },
  gatechief: {
    id: "gatechief",
    name: "黃巾鎮口頭目",
    portrait: "./art/portrait-bandit.png",
    maxHp: 92,
    maxSp: 14,
    atk: 13,
    def: 7,
    spd: 9,
    shields: 3,
    weaknesses: ["spear", "fire", "dark"],
    skills: [
      { id: "swing", name: "橫劈", sp: 0, weapon: "sword", hits: 1, power: 1 },
      { id: "bellow", name: "恫嚇", sp: 6, weapon: "dark", hits: 1, power: 0.55 },
    ],
    gold: 42,
    exp: 58,
  },
  schemer: {
    id: "schemer",
    name: "黃巾偽軍師",
    portrait: "./art/portrait-boss.png",
    maxHp: 88,
    maxSp: 22,
    atk: 12,
    def: 6,
    spd: 11,
    shields: 3,
    weaknesses: ["fire", "fan", "spear"],
    skills: [
      { id: "trick", name: "詭計", sp: 0, weapon: "dark", hits: 1, power: 0.9 },
      { id: "fog", name: "迷陣", sp: 8, weapon: "fan", hits: 1, power: 0.5, aoe: true },
    ],
    gold: 44,
    exp: 60,
  },
  outlaw: {
    id: "outlaw",
    name: "黃巾懸賞賊",
    portrait: "./art/portrait-bandit.png",
    maxHp: 90,
    maxSp: 14,
    atk: 13,
    def: 7,
    spd: 10,
    shields: 3,
    weaknesses: ["sword", "spear", "fire"],
    skills: [
      { id: "slash", name: "亂砍", sp: 0, weapon: "sword", hits: 1, power: 1 },
      { id: "rob", name: "打劫", sp: 6, weapon: "dark", hits: 1, power: 0.6 },
    ],
    gold: 50,
    exp: 55,
  },
  tyrant: {
    id: "tyrant",
    name: "黃巾鄉霸",
    portrait: "./art/portrait-bandit.png",
    maxHp: 95,
    maxSp: 16,
    atk: 14,
    def: 7,
    spd: 9,
    shields: 3,
    weaknesses: ["sword", "fan", "fire"],
    skills: [
      { id: "bully", name: "欺壓", sp: 0, weapon: "sword", hits: 1, power: 1 },
      { id: "shout", name: "喝令", sp: 7, weapon: "dark", hits: 1, power: 0.55, aoe: true },
    ],
    gold: 46,
    exp: 58,
  },
  enforcer: {
    id: "enforcer",
    name: "黃巾探馬頭目",
    portrait: "./art/portrait-bandit.png",
    maxHp: 98,
    maxSp: 16,
    atk: 15,
    def: 7,
    spd: 11,
    shields: 3,
    weaknesses: ["sword", "dark", "fire"],
    skills: [
      { id: "lash", name: "鞭策", sp: 0, weapon: "sword", hits: 1, power: 1 },
      { id: "pressure", name: "威壓", sp: 7, weapon: "dark", hits: 1, power: 0.55, aoe: true },
    ],
    gold: 48,
    exp: 60,
  },
  remnant: {
    id: "remnant",
    name: "黃巾渠帥殘黨",
    portrait: "./art/portrait-boss.png",
    maxHp: 110,
    maxSp: 20,
    atk: 14,
    def: 7,
    spd: 9,
    shields: 3,
    weaknesses: ["spear", "fire", "fan"],
    skills: [
      { id: "crush", name: "砸營", sp: 0, weapon: "staff", hits: 1, power: 0.95 },
      { id: "rally", name: "黃天餘焰", sp: 12, weapon: "dark", hits: 1, power: 0.55, aoe: true },
    ],
    gold: 55,
    exp: 70,
  },
  boss: {
    id: "boss",
    name: "黃巾渠帥",
    portrait: "./art/portrait-boss.png",
    // Phase 1 tuned easier so QA reliably reaches first shield break → phase 2.
    // Phase 2 still gets +atk on break and more aggressive AI.
    maxHp: 140,
    maxSp: 28,
    atk: 14,
    def: 8,
    spd: 8,
    shields: 3,
    weaknesses: ["fire", "spear", "fan"],
    skills: [
      { id: "crush", name: "砸營", sp: 0, weapon: "staff", hits: 1, power: 0.95 },
      { id: "rally", name: "黃天", sp: 14, weapon: "dark", hits: 1, power: 0.55, aoe: true },
    ],
    gold: 80,
    exp: 120,
  },
};

export function heroById(id: string): HeroDef {
  const h = HEROES.find((x) => x.id === id);
  if (!h) throw new Error(`unknown hero ${id}`);
  return h;
}

export const JOURNAL: Record<string, { title: string; body: string }> = {
  start: {
    title: "初入新野",
    body: "八路之中，你選了一人。新野井邊有黃巾的足跡，客棧、商販、里長都還在。",
  },
  inquired: {
    title: "探得弱點",
    body: "黃巾卒怕刀、火、弓。山賊怕槍、火、扇。校尉怕扇、火、弓。渠帥怕火、槍、扇。盾沒崩解前，傷害會被壓住。",
  },
  gate: {
    title: "城門清靜",
    body: "攔路的人已經退開。官道往北，黃旗還在。",
  },
  scout: {
    title: "官道斥候",
    body: "北營可進。校尉巡路，渠帥坐在最裡頭。",
  },
  child: {
    title: "阿娘回家",
    body: "被俘的人已經帶回新野。孩童白天會再出現。",
  },
  boss: {
    title: "北營既破",
    body: "渠帥倒下。新野這一章暫時寫完，列傳仍可繼續在城裡活動。",
  },
  companion: {
    title: "短暫同行",
    body: "第二位英雄暫時加入隊伍。出手順序會輪到兩人，城門與北營可並肩而戰。",
  },
  third: {
    title: "三人同行",
    body: "過路旅人短暫加入。出手順序會輪到三人，城鎮站位也會分開。",
  },
  rested: {
    title: "客棧一夜",
    body: "在新野客棧過了一夜。傷勢與氣力都養回來了。",
  },
  "ch2-start": {
    title: "常山驛",
    body: "趙雲短列傳開始。常山驛外平野有黃巾小帥。",
  },
  "ch2-clear": {
    title: "趙雲列傳・初章既竟",
    body: "平野小帥已除。常山驛暫得安寧。",
  },
  "confluence-start": {
    title: "匯合篇・上路",
    body: "關羽與趙雲並肩走上合流官道。北端有渠帥殘黨。",
  },
  "confluence-clear": {
    title: "八路匯合・序章既竟",
    body: "合流小頭目已除。兩條列傳在此交會。",
  },
  "ch3-start": {
    title: "涿郡驛",
    body: "張飛短列傳開始。鎮口有黃巾鎮口頭目。",
  },
  "ch3-clear": {
    title: "張飛列傳・初章既竟",
    body: "鎮口頭目已除。涿郡驛暫得安寧。",
  },
  "night-talk": {
    title: "圍爐夜話",
    body: "營火邊，關羽與趙雲互訴新野與常山的路。夜深了，氣力稍復。",
  },
  "ch4-start": {
    title: "臥龍岡",
    body: "諸葛亮短列傳開始。新野郊野有黃巾偽軍師。",
  },
  "ch5-start": {
    title: "桃園",
    body: "劉備短列傳開始。桃園外有黃巾鄉霸擾民。",
  },
  "ch5-clear": {
    title: "劉備列傳・初章既竟",
    body: "鄉霸已除。桃園之誓，又堅一分。",
  },
  "ch6-start": {
    title: "許昌郊",
    body: "曹操短列傳開始。許昌官道上有黃巾探馬頭目探聽軍情。",
  },
  "ch6-clear": {
    title: "曹操列傳・初章既竟",
    body: "探馬頭目已除。官道風聲，暫入袖中。",
  },
  "bounty-start": {
    title: "懸賞木牌",
    body: "新野懸賞板上寫著：擊敗黃巾懸賞賊，報官領賞。",
  },
  "bounty-clear": {
    title: "懸賞完成",
    body: "懸賞賊已除，賞金與藥草已到手。",
  },
};
